# Generated by Django 5.2 on 2025-10-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="page_count",
            new_name="pages",
        ),
        migrations.RemoveField(
            model_name="book",
            name="openlibrary_id",
        ),
        migrations.AddField(
            model_name="book",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="first_publish_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="olid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
