# Generated by Django 5.2 on 2025-10-31 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rental",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="rental",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="rental",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who created this rental",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rentals_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("returned", "Returned"),
                    ("extended", "Extended"),
                    ("overdue", "Overdue"),
                ],
                default="active",
                help_text="Current status of the rental",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="rental",
            index=models.Index(
                fields=["user", "book"], name="book_rental_user_id_79ec83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rental",
            index=models.Index(fields=["status"], name="book_rental_status_f9a26b_idx"),
        ),
    ]
