# Generated by Django 5.2 on 2025-10-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_rental_options_rental_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rental",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="rental",
            name="book_rental_user_id_79ec83_idx",
        ),
        migrations.RemoveIndex(
            model_name="rental",
            name="book_rental_status_f9a26b_idx",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="status",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="updated_at",
        ),
    ]
