# Generated by Django 5.2 on 2025-10-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_rental_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rental",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddField(
            model_name="rental",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("extended", "Extended"),
                    ("returned", "Returned"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
